### ISSUE TITLE
Reuse comments instead of posting new ones

### ISSUE THREAD

**Issue by marvinhagemeister** [kuldeepkeshwar/size-plugin-bot#36]
On some PRs with many pushes and commits there is a bit of comment noise caused by `size-plugin-bot`. See https://github.com/preactjs/preact-www/pull/415 for an example of that. I wonder if there is a way to edit an existing comment if there is any instead of always making a new one. That would clean up the thread considerably.

**Comment by kuldeepkeshwar** [comment]
@marvinhagemeister updating the existing comment can have side effects too, imagine someone refers that comment (by bot) in another pr/issue and now bot comes and update the comment as there is a new commit pushed. here context for the previous commit will be lost(although GitHub has comment history feature, this can be very tricky).

Also, if bot keeps on updating the existing comment, I am not sure whether the user will even scroll up to notice what changes bot made in the comment. A new comment always comes at the bottom is more noticeable by the user.

PS Github also understands the fact that too many comments in a pr are not good for UX so they collapse them after a threshold. 

Although I also not a fan of a bot which keeps on bombarding comments in the PR. I need to see how to make it better without introducing any side effect. I am just wondering how other bots do it.

**Comment by developit** [comment]
Personally I'd _much_ rather have size-plugin-bot update a single comment. It'll generally be the first comment on a given PR, which gives it high visibility. Comment references can still be understood via history, or simply by quoting the text.

Currently on a longstanding PR I find it difficult to pick out the actual comments from within all the size-plugin bot comments.

**Comment by kuldeepkeshwar** [comment]
@marvinhagemeister @developit sorry for the delay, I will update it before the weekend.
